In [1]:
import numpy as np

In [3]:
b = np.array([[9.0,8.0,5.0],[3.0,8.0,1.0]])

In [4]:
c= np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [5]:
b.shape

(2, 3)

In [6]:
np.random.rand(4,2)

array([[0.35053883, 0.89393232],
       [0.86890528, 0.04338352],
       [0.4034172 , 0.93324014],
       [0.68276585, 0.00385294]])

In [7]:
np.random.randint(-4, 8, size=(3,3))

array([[-3, -3,  6],
       [-1,  5,  6],
       [ 1,  5,  6]], dtype=int32)

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3, axis= 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)


mathemtics

In [19]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [20]:
a+2

array([3, 4, 5, 6, 7])

In [21]:
a-2

array([-1,  0,  1,  2,  3])

In [22]:
a*2

array([ 2,  4,  6,  8, 10])

In [23]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [24]:
a**2

array([ 1,  4,  9, 16, 25])

In [26]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [37]:
a= np.ones((2,4))
print(a)

b = np.full((4,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [3]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [5]:
import numpy as np
z = np.array([1,2,3,4,5])  # 1d array
print (z)

[1 2 3 4 5]


In [9]:
v = np.array([[1,2,3],[4,5,6]]) # 2d array
print (v)

[[1 2 3]
 [4 5 6]]


In [12]:
b = np . array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
b.shape


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [13]:
v.shape

(2, 3)

In [15]:
z.shape

(5,)

In [17]:
b.size

9

In [18]:
v.size

6

In [19]:
z.size

5

In [20]:
z.dtype

dtype('int64')

In [23]:
g = np.array(["rahul", "n", "murthy"])
print (g)

['rahul' 'n' 'murthy']


In [24]:
g.dtype

dtype('<U6')

In [25]:
z[3]

np.int64(4)

In [30]:
v[1,0]

np.int64(4)

In [34]:
b[2,2] # b[row,coloum] it shows like this 

np.int64(9)

b[0:]

In [35]:
b[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
b[:9]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b[2,2] = 10 
print (b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [40]:
v[1,2] = 7
print (v)

[[1 2 3]
 [4 7 7]]


In [41]:
t = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
np.random.rand(4,2)

array([[0.6220573 , 0.58431649],
       [0.11347536, 0.43290986],
       [0.35942424, 0.83665054],
       [0.46631772, 0.12169006]])

In [11]:
np.random.randint(7, size=[3,3])

array([[3, 6, 2],
       [2, 1, 2],
       [3, 2, 5]], dtype=int32)

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.randint(-4,7 , size = [3,3])

array([[ 6,  0, -2],
       [ 1, -1, -2],
       [ 3,  6, -1]], dtype=int32)

In [21]:
arr = np.array([1,2,3])
r = np.repeat(arr,3,axis = 0)
print (r)

[1 1 1 2 2 2 3 3 3]


In [25]:
R = np.array([1,2,3,4,5])
print(R)
R=R+2
print (R)

[1 2 3 4 5]
[3 4 5 6 7]


In [29]:
R = R+6
print(R)

[1 2 3 4 5]


In [30]:
B = np.array([3,4,5,6,7])
print(B)

[3 4 5 6 7]


In [31]:
R = R+B
print(R)

[ 4  6  8 10 12]


In [36]:
np.sin(np.radians(45))

np.float64(0.7071067811865476)

In [53]:
import numpy as np
g = np.ones((3,2))
print (g)



[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [58]:
G = np.full((2,3),2)
print(G)

[[2 2 2]
 [2 2 2]]


In [59]:
g @ G

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [62]:
c = np.array([1,2,3,4,5])
x = c.copy()
c[0]= 43
print (c)
print (x)

[43  2  3  4  5]
[1 2 3 4 5]


In [65]:
import numpy as np
rahul = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new = rahul.reshape(4,3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
rahuls = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
news = rahuls.reshape(2,3,2)
print (news)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [74]:
rahls = np.array([1,2,3,4,5,6,7,8])
ne = rahls.reshape(2,2,-1)
print (ne)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [77]:
give = np.array([1,2,3])
for x in give :
    print (x)

1
2
3


In [79]:
give = np.array([[1,2,3],[4,5,6]])
for x in give :
    print (x)

[1 2 3]
[4 5 6]


In [83]:
give = np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(give) :
    print (x)

1
2
3
4
5
6
7
8
9


In [82]:
give = np.array([[1,2,3],[4,5,6]])
for x in give :
    for y in x:
        print (y)

1
2
3
4
5
6


In [84]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [85]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [90]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print (arr3)

[1 2 3 4 5 6]


In [95]:
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])
arr6 = np.stack((arr4,arr5),axis = 1)
print (arr6)

[[1 4]
 [2 5]
 [3 6]]


In [98]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
arr9 = np.hstack((arr7,arr8))
print (arr9)

[1 2 3 4 5 6]


In [99]:
arr10 = np.array([1,2,3])
arr11 = np.array([4,5,6])
arr12 = np.vstack((arr10,arr11))
print (arr12)

[[1 2 3]
 [4 5 6]]


In [102]:
import numpy as np

arr01= np.array([1, 2, 3])

arr02 = np.array([4, 5, 6])

arr0 = np.dstack((arr01, arr02))

print(arr0)

[[[1 4]
  [2 5]
  [3 6]]]


In [1]:
import numpy as np

arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


In [2]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [3]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [4]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [5]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [6]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [1]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [3]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])

result = list1 + list2
print(result)

[5 7 9]


In [15]:
Y = np.array([[1,6 ],[2,3]],  dtype=object)
print (Y.shape)

X = np.array([[1,2],[3, 6]] , dtype=object)
print(X.shape)
print (X + Y)

(2, 2)
(2, 2)
[[2 8]
 [5 9]]
